<a href="https://colab.research.google.com/github/jhagopal/MachineLearning/blob/main/kfold_cross_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score

In [22]:
iris = load_iris()
l_score = cross_val_score(LogisticRegression(),iris.data,iris.target)
l_score

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [23]:
np.average(l_score)

0.9733333333333334

In [24]:
rf_score = cross_val_score(RandomForestClassifier(),iris.data,iris.target)
rf_score

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [25]:
np.average(rf_score)

0.96

In [26]:
s_score = cross_val_score(SVC(),iris.data,iris.target)
s_score

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [27]:
np.average(s_score)

0.9666666666666666

In [28]:
dt_score = cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
np.average(dt_score)

0.9666666666666668